export const Questions = [
    {
      prompt: "What is the capital of France?",
      optionA: "Berlin",
      optionB: "Madrid",
      optionC: "Rome",
      optionD: "Paris",
      answer: "D",
    },
    {
      prompt: "Which planet is known as the Red Planet?",
      optionA: "Earth",
      optionB: "Venus",
      optionC: "Mars",
      optionD: "Jupiter",
      answer: "C",
    },
    {
      prompt: "What is the largest mammal in the world?",
      optionA: "Elephant",
      optionB: "Blue Whale",
      optionC: "Giraffe",
      optionD: "Shark",
      answer: "B",
    },
    {
      prompt: "Who wrote 'To Kill a Mockingbird'?",
      optionA: "Harper Lee",
      optionB: "Mark Twain",
      optionC: "J.K. Rowling",
      optionD: "Ernest Hemingway",
      answer: "A",
    },
    {
      prompt: "What is the chemical symbol for water?",
      optionA: "O2",
      optionB: "H2",
      optionC: "CO2",
      optionD: "H2O",
      answer: "D",
    },
    {
      prompt: "In which year did the Titanic sink?",
      optionA: "1910",
      optionB: "1912",
      optionC: "1915",
      optionD: "1920",
      answer: "B",
    },
    {
      prompt: "Which country is known as the Land of the Rising Sun?",
      optionA: "China",
      optionB: "South Korea",
      optionC: "Japan",
      optionD: "Thailand",
      answer: "C",
    },
    {
      prompt: "Who painted the Mona Lisa?",
      optionA: "Vincent van Gogh",
      optionB: "Pablo Picasso",
      optionC: "Claude Monet",
      optionD: "Leonardo da Vinci",
      answer: "D",
    },
    {
      prompt: "What is the hardest natural substance on Earth?",
      optionA: "Gold",
      optionB: "Iron",
      optionC: "Diamond",
      optionD: "Silver",
      answer: "C",
    },
    {
      prompt: "How many continents are there on Earth?",
      optionA: "5",
      optionB: "6",
      optionC: "7",
      optionD: "8",
      answer: "C",
    },
  ];
  